### ISSUE TITLE
core dm_core and dm-core mix

### ISSUE THREAD

**Issue by blshkv** [repology/repology#223]
There are 2 similar ruby packages
https://rubygems.org/gems/dm_core/
https://rubygems.org/gems/dm-core/

repology take them as one and mix different versions

**Comment by AMDmi3** [comment]
Bah! Nice catch. I was wondering about whether it's good idea to normalize _ globally, and here's the answer. Actually, it

**Comment by blshkv** [comment]
There are few more, unfortunately:
https://repology.org/metapackage/spl/versions
https://repology.org/metapackage/unicorn/versions

while ```spl``` is quite short, unicorn (web server vs cpu emulator) looks generic enough

**Comment by blshkv** [comment]
https://repology.org/metapackage/msgpack/versions
 Yet another example. 
You should probably create a list of similar categories in different distributions and use it as a second factor of similarity

**Comment by AMDmi3** [comment]
I beg to differ. One problem is different project merging into one metapackage because of repology name normalization, and another is different projects with similar names. There former is repology problem, while the latter is upstream problem we can counter with rules, but only manually. There are actually hundreds of such packages. Unicorn is pretty nasty, as there's also ruby:unicorn mixed the same way, while it's the same thing. msgpack is probably a mix of msgpack-c, msgpack-c++. I'll fix these eventually.

**Comment by blshkv** [comment]
yeah, it is complicated
http://msgpack.org/ provides few independent libraries for different languages:
dev-python/msgpack 0.4.6 ~0.4.7 0.4.8
dev-ruby/msgpack 0.7.6 ~1.0.1 ~1.0.2 ~1.0.3 ~1.1.0
dev-java/msgpack ~0.5.1 0.6.12
dev-libs/msgpack 0.5.9 ~1.0.0 ~1.0.1 ~1.1.0

**Comment by AMDmi3** [comment]
Everything should be fixed. There's a way to disable `_`→`-` normalization and it fixes dm-core/dm_core problem, and I don't see problems with msgpack either.
