### ISSUE TITLE
ignore date versions in debian packages

### ISSUE THREAD

**Issue by swills** [repology/repology#233]
I notice that the parser ignores dates in versions, for example:

ignoring version which is a date: vimPlugins.undotree/vimplugin-undotree-2017-03-24

but looking at:

https://repology.org/metapackage/creduce/versions

it says that 2.7 is the latest  version based on the debian package version:

https://packages.debian.org/unstable/creduce

But if you look at that version, it's actually "2.7~20170317-1" which is a date as well, because 2.7 isn't released (as of the time of writing this), see the creduce home page:

https://embed.cs.utah.edu/creduce/

Maybe some additional logic is needed to find these versions and ignore them?

**Comment by AMDmi3** [comment]
> I notice that the parser ignores dates in versions, for example:

That's specific to nix parser and is used to throw away known-to-be-non-real-versions. In general though, dates are handled just like any other versions.

> But if you look at that version, it's actually "2.7~20170317-1" which is a date as well, because 2.7 isn't released (as of the time of writing this),

Here we just throw away debian-specific suffix starting with `~`, be it a date or other garbage such as `~dgsg1-1` or `~20120413+hg2813-8`. The problem here though is not a date but the fact that debian package uses nonexisting version 2.7. They could've used e.g. `2.6~20170317` which is pretty common practice to name a snapshot past some official release, and repology would throw way the suffix and handle it as `2.6` which would compare correctly to other repos (other repos could use e.g. `2.6.20170317` which would pose a problem comparing _newer_ to `2.6`, but not in this case).

Unfortunately, there's no way to automatically determine whether maintainer uses fake versions, so the only solution for this is adding a version ignore rule, which I'm going to do here. Parsing releases from upstream (github) would probably help when it's implemented.
