### ISSUE TITLE
perl category versions

### ISSUE THREAD

**Issue by pink-mist** [repology/repology#241]
Would it be possible to use CPAN as the authoritative source for perl category version numbers?
I'm imagining something like:
```
- { family: [everything except cpan], category: perl, ignorever: true }
```

**Comment by AMDmi3** [comment]
Actually we can't even compare perl module versions reliably, even within CPAN itself. Because of broken upstream perl module versioning scheme, 1.1001 may follow 1.1, then 1.2, that breaks all sane comparisons. Because of that some distros mangle versions so they increase monotonically, but that's incompatible with CPAN and other distros. In this broken environment, I don't think stricter rules can fix anything.

Also, I don't like a concept of "authoritative version source". One of repology strengths is finding new versions in unexpected places, which other services (for example, ones looking at upstream) fail to (for example, when upstream moves to another website or a fork). If there's a version of any package newer than upstream that should be most visible and most annoying to all maintainers. This way newer version could be audited and probably switched to.

Also, we can't rely on category (but what you propose can be achieved with e.g.

```
- { namepat: "perl:.*", ignorever: true }
- { family: cpan, unignorever: true }
```
)

The current problem with perl modules is that I've added MacPorts which also uses perl module version mangling and I haven't added verignores for that, fixed just now. With this, most "outdated" package in CPAN should go away, but remaining ones (under 200) still need to be manually audited by maintainers.

[This](https://repology.org/metapackage/perl:anyevent-callback/versions), for example. Version comparison problems non involved, but why the hell Debian ships 0.06 while CPAN has 0.05? Should Debian maintainers be contacted to not use fake version? Should CPAN maintainer be contacted to update CPAN entry? Has it moved to new home off CPAN? Such cases should be fixed upstream, and repology helps find these.

**Comment by pink-mist** [comment]
Oh, I see, makes sense.

In the example you gave it seems it's actually the same maintainer of the CPAN distribution and the Debian package, and he simply updated the version to 0.06 only on Debian for some reason. Very odd.

**Comment by AMDmi3** [comment]
Couple of additional notes:
- macports perl module version ignore is now in effect, remaining obsolete-in-cpan modules either need version ignores or need investigation on where new versions come from
- when version transformations (#14) are supported in the ruleset, we'll be able to demangle mangled perl module versions we currently ignore

**Comment by thesamesam** [comment]
FWIW, we consistently apply a scheme in Gentoo and have a Perl module for it as well: https://metacpan.org/pod/Gentoo::PerlMod::Version.
