### ISSUE TITLE
Outdated determination error on some packages with version postfix

### ISSUE THREAD

**Issue by farwayer** [repology/repology#276]
I don't know the reason but repology consider some packages with version postfix as outdated.
[ruby-google-api-client-0.12](https://repology.org/metapackage/ruby:google-api-client-0.12/versions) displayed well
[ruby-slack-notifier-1](https://repology.org/metapackage/ruby:slack-notifier/versions) displayed outdated

**Comment by farwayer** [comment]
@AMDmi3 Are you sure issue fixed in this commit?
`ruby-google-api-client-0.12` displayed well. The problem is with `ruby-slack-notifier-1` and `ruby-mini_magick-4.5` packages.

**Comment by AMDmi3** [comment]
It takes for commit → deploy → database update. However the commit fixed ```ruby-google-api-client-0.12``` - it was incorrectly displayed as fresh because it was not matched with other packages. Repology does not care of package suffixes currently, outdated is outdated.

There's and idea to make this more clever and tolerate legacy packages (as long as there's an up to date version in the same repository), see #170.

**Comment by farwayer** [comment]
Thanks for the explanation. I thought version postfixes are supported 😞
