### ISSUE TITLE
Ignore development versions of GNOME packages

### ISSUE THREAD

**Issue by jtojnar** [repology/repology#296]
For most GNOME apps, odd minor versions are [development versions](https://developer.gnome.org/programming-guidelines/stable/versioning.html.en#stable-unstable-versions). Fedora Rawhide provides these unstable packages making the packages in other repositories look outdated.

Either another category of packages (unstable) and heuristics (beta, rc in the version, odd minor for GNOME) for detecting packages belonging there should be added or Fedora Rawhide should be ignored.

**Comment by jrmarino** [comment]
I brought this exact topic up privately a few weeks ago.  Nobody wants to see their up-to-date packages marked "outdated" because some unstable repo packaged it as a release.

I suggested the use of regex rules in general, which would be perfect to identify "odd" versions and automatically ignore them.

**Comment by AMDmi3** [comment]
Superseded by #316

**Comment by AMDmi3** [comment]
Would be nice of someone to add a full list of GNOME apps/libs metapackages which are subject to gnome versioning scheme to #316. List of metapackages which have odd minor versions in the wild would also suffice for now.
