### ISSUE TITLE
Fedora pkgdb is being discontinued

### ISSUE THREAD

**Issue by jbicha** [repology/repology#305]
1. Visit https://repology.org/metapackage/webkitgtk/versions
2. See that the latest Fedora Rawhide version is **2.17.90**. Click the webkitgtk4 link next to the version number.
3. The link points to https://admin.fedoraproject.org/pkgdb/package/rpms/webkitgtk4/ with a warning that the site is being decommissioned and a link to
https://fedoraproject.org/wiki/Infrastructure/WhatHappenedToPkgdb

But if I go to https://src.fedoraproject.org/rpms/webkitgtk4 I see that the latest version in Rawhide is **2.17.91**.

**Comment by AMDmi3** [comment]
It's already 2.17.91 in repology. Repology uses package repositories https://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/ as a [package information source](https://github.com/repology/repology/blob/master/repos.d/rpm/fedora.yaml#L91), so my guess is that if repology is only affected because it provides additional [link](https://github.com/repology/repology/blob/master/repos.d/rpm/fedora.yaml#L98) to pkgdb, which will need to be fixed or removed. I still have to read the wiki page though.

**Comment by sitsofe** [comment]
Links may be able to go to https://apps.fedoraproject.org/ e.g. https://apps.fedoraproject.org/packages/fio .

**Comment by jbicha** [comment]
I suggest https://src.fedoraproject.org/rpms/fio

**Comment by AMDmi3** [comment]
I've just changed links to https://src.fedoraproject.org/, but https://apps.fedoraproject.org/packages/fio seem worth adding too, and even a better as a default link, cause it's more user oriented.
