### ISSUE TITLE
Atom feeds of per-maintainer outdated packages and problems

### ISSUE THREAD

**Issue by hartwork** [repology/repology#308]
Hi!

Awesome project, thanks for that! It would be cool if there were Atom feed versions of
* https://repology.org/api/v1/maintainer/sping@gentoo.org/problems
* https://repology.org/metapackages/outdated-by-maintainer/sping%40gentoo.org/

so that I could use my RSS-to-email bridge to get notified of things I should fix/update, automatically.
Are there plans to implement that?

Thanks and best, Sebastian

**Comment by AMDmi3** [comment]
That's actually **the** primary goal for repology development. However, it still requires some huge dependent tasks to be done first, such as implementing delta updates. Currently, whole repology database is rebuilt from scratch on each update, so there's no way to generate changes between "old" and "new" states, which could be then served in the form of feeds.

**Comment by hartwork** [comment]
If the feed would contain entries in chronological order with stable IDs, the diffing could be done by the RSS client, as that is already doing that. So maybe the backend doesn't need diffing for that. What do you think?

**Comment by AMDmi3** [comment]
There's no chronology (as the whole database is created from scrach) and there are no stable IDs (the set of packages which comes from upstream is basically random, with arbitrary order, duplicates, renames etc.). Also such lists (thousands of packages or problems) would be too large for clients to handle.

**Comment by hartwork** [comment]
I expect the per-maintainer lists to be less than thousand entries for humans, maybe even less than 50 in most cases. I would expect a feed reader to be able to handle that and consider it their problem (or a reasons to switch the client) if it does not. What do you think?

**Comment by AMDmi3** [comment]
Still too big.
- You don't want 1000 items pop up when you add the feed.
- You don't want to fetch hundreds of kilobytes each <your favorite feed update interval>

Unfortunately, this will have to wait before the inner workings are refactored. After that we'll have a clean chronological feed of detailed events such as (package XXX max version bumped to YYY in repo ZZZ).

**Comment by hartwork** [comment]
I don't follow in detail, but I'm looking forward to that feature. Good luck!

**Comment by AMDmi3** [comment]
I'd like to hear opinions of how the feed should look like.

The mandatory part is like this, I guess:
- "Package **firefox** is outdated"

But the options of how that can be extended are numerous:
- "Package **firefox** is outdated by version **1.1**"
- "Package **firefox** version **1.0** is outdated by version **1.1**"
- "Package **firefox** version **1.0** is outdated by version **1.1** in repository **AUR**"

Should each version bump be reported?
- "Package **firefox** is outdated by version **1.1**"
- "Package **firefox** is outdated by version **1.2**"
- "Package **firefox** is outdated by version **1.3**"

Should updates be reported?
- "Package **firefox** is at latest version"
- "Package **firefox** is at latest version **1.1**"

Should other events be reported?
- "New package **firefox** **1.1**"
- "Package **firefox** removed"

Should extra details be reported (may be useful if you monitor multiple repos)?
- "Package **firefox** in repository **Gentoo** is now outdated"

How should we handle multiple versions?
Should we handle other statuses (ignored, incorrect)?

**Comment by AMDmi3** [comment]
Yes, problems were also requested in this issue. I'd prefer to not touch them, as whole problems infrastructure should be rewritten, it's too clumsy and crutchy to touch now. Also, we'll have the same issue as #512 here (e.g. we'll need links to original packages). May fix it the same way, though I don't fully like that solution. A room for improvement here as well.

**Comment by davidak** [comment]
>But the options of how that can be extended are numerous:
>
>- "Package firefox version 1.0 is outdated by version 1.1 in repository AUR"

Is the repository of the newer version really helpful for a maintainer? Also what repo should be displayed when multiple have the latest version?

>Should each version bump be reported?

Yes. A maintainer probably always want to be up to date.

>Should updates be reported?

1. No, because the maintainer knows when he has updated a package. It's duplicate information.
2. **Yes**, since other people could update the package. At least in NixOS not only the official maintainer updates packages...

>Should other events be reported?

Again, the maintainer knows when he has added a new package, but might not know his package was removed. So probably **yes**. We still could remove some events when it is too much.

>Should extra details be reported (may be useful if you monitor multiple repos)?

Yes, but keep it sane. The relevant information should be visible instantly and not hidden in a bunch of irrelevant stuff.

>How should we handle multiple versions?

Some big projects maintain multiple stable versions, so **1.0.1 and 2.1.1 could both** have the latest security fixes. But we don't have that information... We only could assume that newly updated packages have recent versions.

Example: https://repology.org/metapackage/linux/information
Compare to: https://www.kernel.org/

We could scrape the information from the website somehow, but i think there is no way to guess what version is LTS or EOL.

So i think the best we can do is to mark the **latest** version and show every other as outdated. "Outdated" can mean that that version is still maintained, so a hint is needed on the site about that.

>Should we handle other statuses (ignored, incorrect)?

Like you see in the linux versions, some repos contain development versions marked with grey background. They shouldn't assumed to be latest. So a status is needed for them. Also there are strange version numbers sometimes that also need some status. So **yes**, something like that is needed to handle such situations.

>I myself, as maintainer, would prefer all options
>We'll also see if that's too verbose, in which case it could be trimmed and/or optionized.

Yes, do it :)

I think it's also helpful to see if it's a **major, minor or patch level update**. Stable or LTS channels often don't do major version bumps.
Sure it can't be always detected, for example with date-based release numbers. Then only say "... is outdated by update to..."

**Gentoo**: package **firefox 1.1** is outdated by **minor version** update to **1.2** in **AUR**

--

Also the entry should have a link to more informations or multiple links.

**Comment by AMDmi3** [comment]
> Is the repository of the newer version really helpful for a maintainer?

Depends. Maybe someone is less trustful for some repos, or is just curious.

> Also what repo should be displayed when multiple have the latest version?

All of them obviously.

> No, because the maintainer knows when he has updated a package. It's duplicate information.

Still useful to make sure it got propagated. There were multiple times I've forgot to actually do the commit of a prepared update, or I've missed `svn` fail with `files out of date` by switching to another work.

> Yes, since other people could update the package. At least in NixOS not only the official maintainer updates packages...

True.

> Yes, but keep it sane. The relevant information should be visible instantly and not hidden in a bunch of irrelevant stuff.

Well each feed entry has the title which should be as short as possible to fit into notificatios and phone screens without wrapping and trimming. But there's also a content part which can be as large as required. However, if we use text format (which I prefer for compatibility) it's not too readable, since there's no way to highlight names and versions.

Anyway, I haven't implemented any additional info in the first version.

> Some big projects maintain multiple stable versions

Well branches were planned to solve this. They are still not fully implemented (just in the marginal form of a single `devel` branch) but it may be time to complete them. There are not too many projects with multiple supported branches, so I don't see to many problems with maintaining them manually, at least at start.

For now though just the highest version in the repository is counted.

> I think it's also helpful to see if it's a major, minor or patch level update

That's not possible, since not all project adhere to semantic versioning, and there's no telling which actually do.

So, the initial version is ready for testing. I plan to test it on myself for a week and then add links to the feeds from maintainer page.

For you that'd be:
- (html) https://repology.org/maintainer/post%40davidak.de/feed-for-repo/nix_unstable
- (atom) https://repology.org/maintainer/post%40davidak.de/feed-for-repo/nix_unstable/rss

no events yet though.

**Comment by AMDmi3** [comment]
> most readers should be capable of basic markup, right?

Yes, but if they don't, people will probably see tags, which is ugly.

> The Atom feed link contains "rss", what is kind of misleading. Is a RSS feed planned? I think more people know and use them.

My understanding is that regardless of actual feed format, _rss_ term is used for them all and more widely known. For the format itself, atom is recommended as newer and more consistent. I don't see any need to add actual rss feed in parallel.

**Comment by AMDmi3** [comment]
> No, RSS and Atom are two different formats.

I know that. The point is that it's common to just call them both rss.

> Most software like blogging software just support both. Should be easy with some library.

It lists atom advantages. Since it's well supported, I see no point to support RSS.

**Comment by davidak** [comment]
>The point is that it's common to just call them both rss.

Really? I have never noticed that. Any examples?

**Comment by hartwork** [comment]
I checkout out "my" feed https://repology.org/maintainer/sping%40gentoo.org/feed-for-repo/gentoo/rss now. My vote for mentioning the outdating upstream version 0.4.0 somewhere and to go with `/atom` or `/feed` for the URL rather than `/rss`.

**Comment by AMDmi3** [comment]
> and to go with /atom or /feed for the URL rather than /rss.

Done.

**Comment by AMDmi3** [comment]
Package version feed is complete. Problems may be added to it later for as a part of large problems refactoring (related #196).

**Comment by hartwork** [comment]
The feed has started to be my fastest source of outstanding package bumps, including some that I would have missed through all other channels. So this feature helps reduce delays on my end already. Pretty awesome, thanks again!
