### ISSUE TITLE
ruby-mini-magick version issue

### ISSUE THREAD

**Issue by farwayer** [repology/repology#346]
Thank you for legacy packages! This is really cool feature. But some problems in parsing still exists.
https://repology.org/metapackage/ruby:mini-magick/versions

![2017-09-28-200807_725x157_scrot](https://user-images.githubusercontent.com/2343101/30980193-c92e6c3a-a488-11e7-9063-410899f6044e.png)

First version should be legacy (because 4.5.1 is the latest from 4.5.x) and second should be outdated.

**Comment by farwayer** [comment]
The same for https://repology.org/metapackage/ruby:slack-notifier/versions

![2017-09-28-201411_669x105_scrot](https://user-images.githubusercontent.com/2343101/30980400-9bad93ca-a489-11e7-9a88-5f44e2d8d5cf.png)

https://repology.org/metapackage/ruby:public-suffix-2/versions
parsed as unique but it is not true

![2017-09-28-201500_1027x101_scrot](https://user-images.githubusercontent.com/2343101/30980429-b72dca34-a489-11e7-9a26-c8351f9433b3.png)

**Comment by AMDmi3** [comment]
Thank you for the report. I get what the problem is, but not sure how to deal with it yet. The case when a repo has preserved legacy version, but no latest one was not expected at all. Probably more complete branches support (which is planned) can help.

I've also added a rule to merge separate `ruby:public-suffix` 2.x packages.

**Comment by AMDmi3** [comment]
#398 is done, so we can now remark these packages as legacy.
