### ISSUE TITLE
Rules for MinGW on MacPorts

### ISSUE THREAD

**Issue by mojca** [repology/repology#383]
The MinGW packages for MacPorts are split in a weird way. There's `mingw-w64` which is some kind of a meta-package and is at the same version as `*-w64-mingw32-crt`, `*-w64-mingw32-headers` (and soon `*-w64-mingw32-winpthreads`).

Then `*-w64-mingw32-gcc` is basically `gcc` cross-compiler. And `*-w64-mingw32-binutils` is basically `binutils` for cross-compiler. I don't know against which packages these are supposed to be compared and I'm not sure how to write the rules for such a split, but it would be nice to correct this.

(Plus there's a bunch of abandonware `i386-mingw32-*`.)

**Comment by AMDmi3** [comment]
I'm a bit hesitant regarding these for now. At the one hand, they should be merged with corresponding gcc/binutils along with all cross-** packages. At the other hand, these are still useful as separate mentapackages, otherwise the information on which repos have mingw support is hidden. We could both, but it's not possible to attach a package to multiple metapackages yet.

**Comment by AMDmi3** [comment]
Moved to https://github.com/repology/repology-rules/issues/8
