### ISSUE TITLE
Add npackd repository

### ISSUE THREAD

**Issue by jaens** [repology/repology#430]
A Windows package manager with >900 packages.

Looks like dumps available here:
https://npackd.appspot.com/rep

**Comment by AMDmi3** [comment]
This only seem to only be partially usable and will require bunch of rules, because it does not contain common package names. For instance:

```xml
<package name="org.apache.httpd.HTTPServer">
    <title>Apache HTTP Server</title>
    <url>http://httpd.apache.org</url>
    <description>HTTP server. The server runs on the port 8083
i686</description>
    <icon>https://lh6.googleusercontent.com/-t2wQIA3Fpl0/UZ8Z9KC2tbI/AAAAAAAACD0/i1tgHOh9AX4/s800/apache.png</icon>
    <license>org.apache.ApacheLicense2</license>
    <category>Tools</category>
</package>
```

we cannot use either package `name` as it contains this `org.foo.bar.baz` garbage in most cases, and `title` often contains full human readable project name which is not a package name either.

**Comment by jaens** [comment]
Yeah, unfortunately... Just filed this here in case someone is interested.

**Comment by AMDmi3** [comment]
Yes, but that's not reliable, so it cannot be used for automatic package merging, just as a hint; manual rules would still be required. Matching by homepage may be seen on the site under metapackage's `Related` tab.

Anyway, I'll check this out. If it only requires manual ruled for a small fraction of packages, that would be acceptable.

**Comment by AMDmi3** [comment]
Done. Related #658, #863.
