### ISSUE TITLE
wikidata is absolutely absurd

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#444]
If the answer to any report that has false positives due to the unreliable (due to uncontrolled human access) wikidata is "edit wikidata", that answer is ABSURD.

From what was said on the problem report is:
1) wikidata is by definition human created
2) access is free to anyone in the world

Such unreliable and insecure repositories should not affect controlled and tested repositories.
While the value of wikidata can be easily debated (as in, what does this repo provide that the other 100+ repositories don't?), it's fine to leave as long as it doesn't contribute to version information.

But more importantly: The addition of wikidata to the repology caused regressions.  It is absurd to ask users to fix once good data by editing wikidata.  The decision to include this repository wasn't ours, so why should we be expected to fix the mess it caused?

This is an EXTREMELY bad idea, so awful that I can't even see any other point of view.  Often I can see where somebody is coming from, but I can't figure out what universe that telling us to fix wikidata in order to restore repology is a good idea.

&lt;sarcasm> and nice touch to disable reports on wikidata BS so we can't provide feedback there &lt;/sarcasm>

**Comment by AMDmi3** [comment]
As I've already mentioned, Wikidata is probably **the most** reliable data source out of everything repology supports, because it's purpose is to provide accurate data and it doesn't have limitations of repositories (which purpose is to deliver packages and not version information), such as version schema restrictions which require mangling of upstream version, need for snapshot versions with random schemas, package naming inconsistencies etc.

> While the value of wikidata can be easily debated

No it can not. In addition to what's stated above, it provides some unique pieces of data such as stable version state, and obviously there are projects for which it reports new versions faster than anyone else.

> wikidata is by definition human created

As any other repo.

> access is free to anyone in the world

Which means it can be updated and fixed faster than anything else.

> Such unreliable and insecure repositories

There's nothing stopping any other repository from submitting any kind of incorrect data.

> The addition of wikidata to the repology caused regressions

Addition of **every** repository causes regressions.

> but I can't figure out what universe that telling us to fix wikidata in order to restore repology is a good idea.

It's very easy. Either I add the rule and we end up with two regressions: one remains in wikidata, another added to repology (since every rule has maintenance and CPU cost), in addition your time is spent for creating the report and waiting for it to be processed and my time is spent for processing it. Or you fix wikidata, leaving us with no regressions, less your time spent and no my time spent. What is "ABSURD" is you wasting more of everyone's time for the argument.

> and nice touch to disable reports on wikidata BS so we can't provide feedback there

I've already stated multiple times that reports are no place for discussion. Since you obviously do not understand words, I have to turn to technical measures.

**Comment by jrmarino** [comment]
> As I've already mentioned, Wikidata is probably the most reliable data source out of everything repology supports, because it's purpose is to provide accurate data and it doesn't have limitations of repositories (which purpose is to deliver packages and not version information), such as version schema restrictions which require mangling of upstream version, need for snapshot versions with random schemas, package naming inconsistencies etc.

Who is the benefactor of wikidata in repology?
Repology helps wikidata authors improve their entries. 
I am a prime user of repology and I can state with certainty that wikidata does nothing for me; it is a liability

> No it can not. In addition to what's stated above, it provides some unique pieces of data such as stable version state, and obviously there are projects for which it reports new versions faster than anyone else.

As we've seen with distrowatch, reporting "faster" is not good if it reports faster than upstream does.

> wikidata is by definition human created [As any other repo.]

Wrong!  Any other repo actually builds packages.  If the data is wrong, the package doesn't build.  Wikidata will accept any crap data without validation.  Thus, it is NOT like any other repo.

> Which means it can be updated and fixed faster than anything else.

No, that means it can be corrupted intentionally and it's insecure.  I honestly cannot understand how you would even consider uncontrolled data acceptable.  

> There's nothing stopping any other repository from submitting any kind of incorrect data.

what??  Every repository I know has vetted committers.  If somebody went rogue, they would lose their commit bit.  Sound familiar?  Every repository limits data changes to trusted sources.  Yes, the scrutiny on any single submission might be loose, but the responsibility lies with the committer.  Wikidata is not like the others.

> It's very easy. Either I add the rule and we end up with two regressions: one remains in wikidata, another added to repology (since every rule has maintenance and CPU cost), in addition your time is spent for creating the report and waiting for it to be processed and my time is spent for processing it. Or you fix wikidata, leaving us with no regressions, less your time spent and no my time spent. What is "ABSURD" is you wasting more of everyone's time for the argument.

*your* decision to add wikidata to repology as an equal repository caused a regression.  Why is that my fault, or the fault of any other maintainer from another port that regresses from that decision?  I don't blame you from wanting to avoid the work.  I blame the decision to allow wikidata versions to override.  Display them, fine, but as a blanket ignore.   Again, WHO ACTUALLY BENEFITS FROM WIKIDATA?

> I've already stated multiple times that reports are no place for discussion. Since you obviously do not understand words, I have to turn to technical measures.

Or maybe your report mechanism is too simple.  Or maybe your philosophy too draconian.  It is not probable that your opinion is 100% right forever and everyone else is 100% wrong.  Expecting heavy users of repology to fix a 3rd party site due to questionable decisions by repology is a bad decision.  If you took a poll, I'd bet nobody wants to edit wikidata.  It's too much to expect.  And shutting down feedback isn't a good long term play.  "my way or highway" usually doesn't end up well.

**Comment by AMDmi3** [comment]
> Who is the benefactor of wikidata in repology?

Like any other data source, it contributes to package data completeness and accuracy, so it benefits all repology users.

> Any other repo actually builds packages. If the data is wrong, the package doesn't build

No. Not all repositories build packages. Even if they do, data may be present in repository even if the package does not build. And even if it does, there's nothing which enforces package version to be correct.

>  Every repository I know has vetted committers. If somebody went rogue, they would lose their commit bit

Wikidata does the [same](https://www.wikidata.org/wiki/Wikidata:Vandalism). And, as a Wikimedia project, it has the most established mechanisms do deal with vandalism. Moreover, as already mentioned, repositories do allow data distortion (like version and package name manging) for their own needs and this, while definitely causing regressions for Repology, will unlikely be considered a problem and fixed in upstream. However there's no such problem with Wikidata, as incorrect data is to be and can be fixed at once.

The least trusted sources for Repology are actually repositories which are maintained by a low number of people. There's really nothing preventing them from submitting any kind of garbage data.

> your decision to add wikidata to repology as an equal repository caused a regression

As already mentioned, regressions appear after adding **any** new data source. They also appear by themselves as the time passes and data is updated. They are expected and there are ways to deal with them. There's nothing specific to wikidata here, and, as I've substantiated, it's **least** prone to them compared to other sources. It is going to stay on the equal terms as any other source, period.

The regression could be fixed like many others before. However, in this case it can be fixed in much faster and efficient way, which you for some strange reason deliberately ignore.

**Comment by jrmarino** [comment]
I absolutely refuse to update wikidata.
You marked my report on json-glib as "invalid"
This was inaccurate.  The report is completely valid.  There was a regression.
However, you essentially marked it "WONTFIX".
Since you said the solution is "** YOU ** fix it", and I refuse to touch wikidata (and I'm actually amazed that you even suggested it), json-glib continues to be broken.

Maybe you're using repology as leverage to help out the wikidata project, I don't know.  I refuse to be extorted that way.  I'm not doing it.  It's enough that I spend extra time and effort with reports that don't directly affect ravenports (just for the overall good of the project).  

> The least trusted sources for Repology are actually repositories which are maintained by a low number of people

Ravenports has to be an exception to that rule.

**Comment by AMDmi3** [comment]
If you don't want to help, I guess you'll have to wait for someone other to fix it.

**Comment by jrmarino** [comment]
yep.  And now, nobody can report additional (non-wikidata) json-glib issues because you shut down the reporting on it.

I will help you and repology.  I will **not** help a third party repository that I care nothing about.

**Comment by AMDmi3** [comment]
Helping me and repology implies fixing wikidata here. You could be wiser and stop posturing.

**Comment by jrmarino** [comment]
I mean help you DIRECTLY.
By the way, your analysis of json-glib was wrong.
It's not even pointing to the correct entry.
json-glib is pointing to gstreamermm entry.  (https://www.wikidata.org/wiki/Q47270524)
That's a 100% repology error.

> You could be wiser and stop posturing.

Believe me, I am not posturing.  I can also state "you could be wiser" in your handling of this.  Your assumptions about what people can and should be expected to do are out there.

**Comment by AMDmi3** [comment]
> I mean help you DIRECTLY.

If you want to help, you don't care of whether it is direct or indirect. You don't want to help at all.

> That's a 100% repology error.

No it is not. Wikidata gstreamermm entry lists glib-json packages, that is the cause of the problem.

**Comment by jrmarino** [comment]
I do not care if wikidata dies tomorrow.  I do not care about it all.  As I said, as far as I am concerned, it is a liability and if I had a vote, it would be removed from repology.  I care if repology's data is wrong.  That's why I recommended blocking wikidata, to restore correct data.

> No it is not. Wikidata gstreamermm entry lists glib-json packages, that is the cause of the problem.

the repology filter has connected gstreamermm to glib-json.  That's the filter's fault.  If the connection causes bad data, then remove the connection.  Or fix the filter.  it sounds like wikidata should be listed glib-json on it's on, but it's not, so there's an apparent mismatch.

I know nothing, but at first blush, this definitely looks like repology's fault for establishing a connection between gstreamermm and glib-json.  You have control over that.  Break the connection.

**Comment by AMDmi3** [comment]
> the repology filter

There's no such thing. I've explained which the problem is.

**Comment by jrmarino** [comment]
the "filter" is the analog to what repology uses to populate ravenports (repology.json).  Whatever data that tells repology that json-glib maps to https://www.wikidata.org/wiki/Q47270524 .

I didn't read the wiki page.  I just know that json-glib <> gstreamermm.  There should be no link in json-glib to wikidata at all.

**Comment by AMDmi3** [comment]
> Whatever data that tells repology that json-glib maps to https://www.wikidata.org/wiki/Q47270524 .

This data is package references in that entry.

**Comment by jrmarino** [comment]
So is that happening all over wikidata?
Any reference to dependency creates a link in repology between some unrelated software?
wikidata doesn't dedicate one entry to each package? (in other words, there's no 1:1 relationship between wiki entries and repology packages?)

I don't see how this isn't repology's failure.  If there's no dedicated entry for json-glib, there shouldn't be a link from json-glib to wikidata, full stop.

**Comment by AMDmi3** [comment]
For software projects, Wikidata (may contain) data on their package names for several distros. Repology uses that to map Wikidata entries to metapackages. If an entry contains invalid package names, it will be linked to invalid metapackage.

**Comment by jrmarino** [comment]
sounds like you should be prepared to filter those out.  There's no difference between that and "9999" versions and other invalid data done by other repositories.  Yes, it would be nice if somebody fixed the problem upstream but you can say that about most "ignored" entry out there.

I am sure you are just as tired as I am of the subject.
Summary:
1) there's a generic issue wikidata
2) there's a specific issue identified with json-glib
3) I'm not going to touch wikidata
thus: json-glib remains busted in repology indefinitely.

The issue is known; I've done my job and you already marked my report "invalid".  we're at an impasse so I'm dropping it.

**Comment by AMDmi3** [comment]
>  There's no difference

There is. While "9999" are normal and expected (e.g. for Gentoo), incorrect packages are not normal for Wikidata.
