### ISSUE TITLE
AUR packages invent versions

### ISSUE THREAD

**Issue by ilovezfs** [repology/repology#471]
I keep seeing cases of AUR packages that invent new versions that do not exist and are newer than the actual current upstream version of the software. As a result, the outdated status in repology ends up being difficult to use unless I literally filter out everything that AUR packages.

**Comment by AMDmi3** [comment]
This report is pointless. Each incorrect version should be reported and will be processed individually.

**Comment by ilovezfs** [comment]
I can't very well sit there reporting every version someone invents out of the sky. I'd suggest treating AUR as "ignore" across the board.

**Comment by ilovezfs** [comment]
It's like this over and over: https://repology.org/metapackage/aldo/versions

**Comment by ilovezfs** [comment]
https://repology.org/metapackage/betty/versions

**Comment by ilovezfs** [comment]
https://repology.org/metapackage/bzr-rewrite/versions

**Comment by ilovezfs** [comment]
https://repology.org/metapackage/cfr/versions

**Comment by AMDmi3** [comment]
> I can't very well sit there reporting every version someone invents out of the sky. I'd suggest treating AUR as "ignore" across the board.

There are fake versions in each and every repository, and no, we won't ignore whole repositories because of that. I don't see any more problems with AUR than with any other repo. 

> https://repology.org/metapackage/cfr/versions

This one is is invalid.

**Comment by AMDmi3** [comment]
Just for the note, now that we have a dedicated status for incorrect (fake/invented) versions, it's clear that AUR is not the leader in it. Leaders are Sisyphus, Fedora, and Mageia.

**Comment by ilovezfs** [comment]
Time for a wall of shame!

**Comment by ilovezfs** [comment]
@AMDmi3 are there any fake/invented versions you've identified in Homebrew? I'd like to try to fix them if possible because we don't want to be doing that.

**Comment by AMDmi3** [comment]
Here's a [list](https://repology.org/metapackages/?search=&maintainer=&category=&inrepo=homebrew&notinrepo=&minspread=5&maxspread=&problematic=on), but it's quite small, only one version is incorrect. Note that ignored (grey) versions are not necessary problematic (since snapshots (which are often necessary evil) are marked like this), but still worth looking at as there are still incorrect versions marked as ignored too. For instance, `minio` may need fixing as it likely uses incorrect version format.

Also, [here's](https://repology.org/metapackages/?search=&maintainer=&category=&inrepo=homebrew&notinrepo=&minspread=&maxspread=&newest=on&newestsinglefamily=on) a list of metapackages which are newest only in Homebrew or Linuxbrew - this is by no means a list of fake versions, most of these is homebrew just being the freshest, but if there's a fake version, it'll likely be among these. You can start with smaller [list](https://repology.org/metapackages/?search=&maintainer=&category=&inrepo=homebrew&notinrepo=&minspread=5&maxspread=&newest=on&newestsinglefamily=on) of most wide spread packages. (I've just noticed that this list works incorrectly wrt. devel versions, please ignore them for now, I'll fix it soon).

If an incorrect version is detected, there's many of ways to deal with it:
- Snapshots are marked with `ignored`. There's also an effort to create a single scheme for  snapshot versioning which would be non-ambigous and comparable between repositories: https://github.com/repology/repology/issues/345, you could participate if you want.
- Real fake versions are marked with `incorrect` (or fixed in the repo, which would be great)
- There's a way to mark metapackages which have no upstream versioning scheme ([like this](https://repology.org/metapackage/x264))
- Of course some packages may require splits
