### ISSUE TITLE
Add direct links to the packages in the "repository problems" page

### ISSUE THREAD

**Issue by waldyrious** [repology/repology#512]
The "Repository problems" page ([example](https://repology.org/repository/wikidata/problems)) includes the package name but not the link. For contrast, see the "Versions" page ([example](https://repology.org/metapackage/0ad/versions)), which does contain a direct link to the package's page in the repository's website. Having those links in the "Repository problems" page would be convenient for addressing the issues.

I tried to submit a PR but got a bit lost in the code. From:

https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/repologyapp/templates/metapackage-versions.html#L34

...I can see that the `package_link()` macro is used to produce the link in the "Versions" page. However, in the "Repository problems" page [the object is a `problem`](https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/repologyapp/templates/problems.html#L25), which doesn't sound like the kind of object `package_link()` would expect.

Granted, I noticed from:

https://github.com/repology/repology/blob/252fc436e665a46d084614dcad623a4a8c669b77/repologyapp/templates/macros.html#L29-L35

...that the first argument to the macro would need to have a `repo` field, which apparently the `problem` data struct [does](https://github.com/repology/repology/blob/8abe96826ee490f152f39919b7c8c559d99ab47a/sql.d/problems.sql#L35); however, it apparently would also need to be a data structure that can be passed to [`pkg_format`](https://github.com/repology/repology/blob/371fb0976d74267291f448ebcfa928820a884581/repologyapp/template_helpers.py#L75)... I didn't follow the trail further since it already feels a bit hackish to pass a `problem` object to `package_link()`, rather than a `package` object.

I'd welcome any hints as to how to proceed.

**Comment by AMDmi3** [comment]
Nice work here, but unfortunately it's not easy. You got it right, to get the link you need both repository metadata (which contains link templates) and a complete package (which is used to fill the template). Unfortunately, package is not available in the problems view in any form, and it's not possible to link it directly, as packages do not have any unique IDs - this was never needed because for most repos it's not possible to track single package between updates, so on each update we always replace whole set of packages.

To fix the issue we probably need to add autoincrement primary key column to packages table, and use it to reference specific package from a problem. The ids will be regenerated on each update but as problems are regenerated to there's no problem.

Also since QueryManager does not know how to return Package along with unrelated data (which would happen when you query problem + its package data) and teaching it would be overcomplication (so let it just return a dict), PackageFormatter should be taught to work with a simple dict instead. Probably just an easy isinstance check.

**Comment by waldyrious** [comment]
Glad to hear my instincts weren't misguided :) Let me know if there's something straightforward (for someone unfamiliar with this code and Flask in general) in your plan that I can help out with.

**Comment by AMDmi3** [comment]
Well I've tried my best to mark some issues with `good first issue` label, you can probably look at them.

**Comment by waldyrious** [comment]
That's great, kudos for doing that :) I was asking specifically in regards to this particular issue, but I'll make sure to take a look at the other `good first issue`s as soon as I am able to devote some time to tinkering with this project.

**Comment by AMDmi3** [comment]
Oh, I though I've described what should be done here in enough detail, but of course my perception is biased. This issue needs:

- Adding autoincement primary key `id` column to `packages` table: https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/sql.d/schema.sql#L50 and corresponding `package_id` column into `problems` table: https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/sql.d/schema.sql#L328
- Modify queries that create problems (https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/sql.d/update-finish.sql#L162 (there are 5 of them) to store the package id along with the problem.
- Modify problem retrieval queries https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/sql.d/problems.sql#L31 to return package data (adding an `INNER JOIN` with `packages` table). By default there will be conflict with problem data (since both package and problem have `repo`, `name`, `effname` fields), you'd need to `SELECT packages.*, maintainer, problem` to resolve it.

Now in the webapp you'll have a dict which contains all `package` data, which you can feed to `pkg_format()` filter. However, since it expects `Package` object and not a dict, you'll need to modify it first https://github.com/repology/repology/blob/840c1ba6b0d7ddc67d4fd1070cd8f96aef1a60bd/repology/packageformatter.py#L31 with something like

```patch
-pkg = args[0]
+pkgdata = args[0].__dict__ if isinstance(args[0], Package) else args[0]
```
and change the rest to expect dict
```
 if key == 'name':
-    value = pkg.name
+    value = pkgdata['name']
```

That should do it.

**Comment by waldyrious** [comment]
That was an awesomely detailed write-up, thanks a lot! I'll take a stab at this as soon as I have the bandwidth.
