### ISSUE TITLE
Re-defining the meaning of outdated?

### ISSUE THREAD

**Issue by hartwork** [repology/repology#539]
Hi Dmitry,

I use repology to keep track of updates I missed on my packages but also to find what distro still needes to update their packaging of my own projects. Pretty cool thing, very useful.

I noticed that through the eyes of repology.org a package is _outdated_ if a version lower than the latest exists, e.g. if distro Gentoo has package `grub2-theme-preview` in version 1.3.*1* and 1.3.*2* packaged and 1.3.*2* is the know latest, repology will list and count grub2-theme-preview as outdated for both Gentoo and the [maintainer of that package](https://repology.org/metapackages/?maintainer=sping%40gentoo.org&outdated=1) (me in this case). While a "contains outdated version" view could still be useful for clean-up purposes, shouldn't a package that contains the latest upstream version  (or higher for post-release snapshots) be considered up to date and not be counted as updated?

With [my own account](https://repology.org/maintainers/?search=sping%40gentoo.org) the summary says:
```
                   Total   Outdated   Up to date
sping@gentoo.org      53         14        73.6%
```
When I then follow the link to [14 outdated packages](https://repology.org/metapackages/?maintainer=sping%40gentoo.org&outdated=1), it turns out that _only two of them_ do not have a package that is (at least) as new as the latest version. So there's a lot less to do than updating 14 packages for me.

So I would argue that a package that has versions as new as the latest upstream is up to date. Would be awesome if that could be fixed.

What do you think?

Best, Sebastian

**Comment by AMDmi3** [comment]
Well it's true that there's some ambiguity here. Repology logic targets the case when a maintainer maintains packages of a single project in multiple unrelated repositories. In this case we want to report each package which are not at the latest version.

This changes if the repositories are related though. Like Funtoo and Gentoo, as in this case - outdated version in Funtoo is what makes packages maintained by you marked as outdated.

There's no problem with the list of outdated metapackages - what you need is just to [specify a repository](https://repology.org/metapackages/?search=&maintainer=sping%40gentoo.org&category=&inrepo=gentoo&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on). However I admit that the statistics is incorrect in this case. This can be fixed by aggregating by repository families, I'll see what can be done.

**Comment by hartwork** [comment]
Specifying a dependency worked to get my personal todo list to the point, good to know!
I'm hoping for a fix to the outdated count summary per maintainer, midterm. Thanks in advance!

**Comment by AMDmi3** [comment]
While I quite forgot of this issue, it was recently risen again in #925, and it needs be fixed along with #655 soon to prevent further problems of derived repositories affecting the quality of service for original ones.

> This can be fixed by aggregating by repository families

Another idea would be to pick the repository with best statistics, assuming it's where the maintainer is most active and it's most representative. The selection should probably be based on absolute number of newest packages, so it's not affected by partialy derived repositories, legacy repositories and individual package imports (e.g. when another repository has better "newest" percentage because it has much smaller number of packages). But maybe it's too complicated, some experiments are needed. Comments also welcome.

**Comment by AMDmi3** [comment]
> Another idea would be to pick the repository with best statistics

It seems that this is actually the only way, as aggregation of all repositories would contain packages likely to be no longer maintained by this maintainer.

**Comment by AMDmi3** [comment]
Deploying the solution now. It turned into a nice refactoring of maintainer/maintainers pages, which has many other benefits.

We now prefer per-repository statistics for a maintainer. Instead of generalized number of packages maintained [in all repos], per-repository statistics is now displayed on maintainer pages, which also amalgates **Package lists** section with links to specific projects lists (all/newest/outdated/problematic/unique/with related etc. for specific maintainer [and now in each repo]) and **Repositories** section with marginal per-repository counters and links to feeds.

For maintainers list, we have to pick a single "most representative" repository, as explained above. To pick the best repository, we rank them by a number of newest packages for a maintainer, then by number of outdated packages (in reversed order). That is - the best repo for maintainer is where there are most latest packages and least outdated packages.

From the first glance, this logic works acceptably. E.g. for Gentoo maintainers, Gentoo is picked instead of Funtoo, and for FreeBSD maintainers, FreeBSD is picked more than DPorts. I'm worried about Debian/Ubuntu maintainers, for which Raspbian and Deepin are picked in most cases, because these distros tend to preserve packages which are removed from newer versions of Debian/Ubuntu. Having more newest packages, they are picked as best, then they may spoil statistics by having more outdated packages as well.

If there are complaints (and I'm pretty sure these will follow), we'll probably have to remove all/most statistics from the maintainers list. I currently don't have another solution:

- Switching back to some kind of aggregate statistics - won't work as it's still account packages in outdated repositories, migrated packages and dropped packages.
- Allowing maintainer to pick preferred repository - won't work, as apart from requiring implementing complicated registration mechanism (which I don't want), it will not satisfy people who don't want to register on another fscking site which displays incorrect information on them to make it stop. Additionally, this would require regular updates of "preferred repository" as new versions of e.g. Ubuntu are released.
- Manually marking some repositories as derived - won't work as relationships between repositories are much more complex than just "A is an outdated copy of B" (explained in #925).
- Using actual maintainer activity as a source for picking the best repository. E.g. pick the repository in which maintainer's packages are updated faster. Won't work in most cases as
  - It requires enough statistical data to be gathered, which is not available in most cases (little packages maintained and infrequent software releases)
  - It's prone to lag (e.g. when new version of Debian/Ubuntu is released, maintainers are switched to it with delay, different for every maintainer)
  - Prone to update process peculiar properties, which may make genuine repositories show larger package update lag than derived ones, due to repository metadata update frequency, repology update frequency, network problems etc.
