### ISSUE TITLE
Add support for Exherbo Linux

### ISSUE THREAD

**Issue by tgurr** [repology/repology#630]
Would be great to have Exherbo Linux added as well.

Package database (including unofficial repositories) at: https://git.exherbo.org/summer/
Official git repositories at: https://git.exherbo.org/

**Comment by Cogitri** [comment]
Oh, yeah, had hoped @tgurr would deal with this. Anyway, how is support for Gentoo implemented? Exhereses (our package format) are sort of similiar to ebuilds, so I guess we could re-use some stuff?

**Comment by Cogitri** [comment]
Yep, exhereses are guaranteed to start with the name of the subdirectory they are in and end in either:
* -packageversion
* -scm (those should be ignored, I suppose)
* _alpha/beta/rc

They always end with `.exheres-0`

**Comment by AMDmi3** [comment]
This seems to work pretty well. One last question, what's relationship between Gentoo and Exherbo repositories? Can/are ebuilds copied from one to another? Is common for exhereses to be based on ebuilds? Or are these developed mostly independently?

I need an understanding of that to decide whether I could reuse (package renaming/merging/splitting  and version transformation/ignoring) rules already present for Gentoo for Exherbo, and whether Gentoo and Exherbo should be in the same family as e.g. Debian and Ubuntu which share most packages.

**Comment by Cogitri** [comment]
> One last question, what's relationship between Gentoo and Exherbo repositories?

There isn't much of a relationship anymore. Exherbo split off Gentoo 2008-ish and since that we basically don't exchange much code. But because Exherbo sort of origins from Gentoo (in the beginning it mostly was Gentoo with some additions Exherbo devs wanted, but couldn't implement in Gentoo), we still share some stuff, like ebuild naming techniques.

>  Can/are ebuilds copied from one to another?

No, we have different metadata variables:

SUMMARY instead of DESCRIPTION
PLATFORMS instead of KEYWORDS
OPTIONS instead of IUSE
DEPENDENCIES instead of DEPEND
etc. etc.

Also, we don't support eclasses (Gentoo's way to share code between ebuilds by inheriting code from shared eclasses), so ebuilds can't be used in Exherbo

>  Is common for exhereses to be based on ebuilds?

We strongly encourage users to not copy blindly from ebuilds (or any other source, this isn't limited to ebuilds, one could copy from PKGBUILDS or similiar stuff as well), but it is possible to copy certain things from an ebuild, if one desires so (e.g. what dependencies does package X have, what is its homepage etc.). However, because of the differences between exhereses and ebuilds one can't copy the ebuild one by one.

> Or are these developed mostly independently?

Yes, they are always developed independently, but sometimes contributors decide to get information from ebuilds or other distros (in which case they leave a copyright line about that in the exhereses)

> I need an understanding of that to decide whether I could reuse (package renaming/merging/splitting and version transformation/ignoring) rules already present for Gentoo for Exherbo

Exherbo still has similarities to Gentoo, so I guess most of the code could be reused.

> and whether Gentoo and Exherbo should be in the same family as e.g. Debian and Ubuntu which share most packages.

Hm, Exherbo really doesn't have many connections to Gentoo anymore (in fact, I guess we sort of "compete" for devs?), so I feel like Gentoo and Exherbo don't really belong in the same family.

One more thing: We have split repositories, meaning that for repology to check for package versions it would first have to fetch all of the repositories. What would be the preferable way to do this?

**Comment by AMDmi3** [comment]
> Exherbo still has similarities to Gentoo, so I guess most of the code could be reused.

A test showed that we can reuse wildcard rules (adding `perl:`/`python:`/`haskell:` prefixes based on category), and individual Gentoo rules do not apply, so we can use separate ruleset. That is convenient.

> so I feel like Gentoo and Exherbo don't really belong in the same family

Yeah, it looked the same for me.

> One more thing: We have split repositories, meaning that for repology to check for package versions it would first have to fetch all of the repositories. What would be the preferable way to do this?

That's not a problem - repology can fetch multiple sources for a single repository. Although a manual action will be required when repository is added or removed.

> Also, we do have metadata files, which look like this: https://paste.pound-python.org/show/iD51J3lh5SBzj3lQglgU/

If it's not available from the repositories we won't be able to use it. Also it doesn't have much data apart from what we can parse from directory tree (summary could be used, but homepage/download URLS are actually the most desired).

Anyway, Exherbo support will be deployed today.

**Comment by Cogitri** [comment]
Awesome, thanks! :)

**Comment by AMDmi3** [comment]
> Alright. How would that manual action look like?

Updating this list:

https://github.com/repology/repology/blob/287dec0888cd3443b0255afd5cc2ba5d43624b64/repos.d/exherbo.yaml#L11-L42
