### ISSUE TITLE
Missing ruby packages from RubyGems

### ISSUE THREAD

**Issue by nemaniarjun** [repology/repology#634]
I am working on a Gsoc project with [coala](https://github.com/coala/coala). You can view the full project description [here](https://projects.coala.io/#/projects?project=automation_of_dependency_management_using_repology&lang=en)

How does Repology fetch package information from RubyGems? 
Many gems seem to be missing. Repology shows 2670 total metapackages in the rubygems repository, while RubyGems.org/stats seems to show 144,034 total gems. 

I want to add a metapackage to Repology (for example: [csvlint](https://github.com/theodi/csvlint.rb))
which is a Ruby Gem and can be found on RubyGems. 

I thought the best way to add packages to Repology is via making an entry on wikidata (https://www.wikidata.org/wiki/Q54880870) but there is no AUR package for the gem (which is needed as per our previous discussion about Wikidata and fetching entries from it). This is not a single case as this happens with other gems like brakeman and haml_lint. 

I would also like to know if there are any plans on adding NPM as a repository? I would like to help if there are any plans. :)

**Comment by AMDmi3** [comment]
> Many gems seem to be missing. Repology shows 2670 total metapackages in the rubygems repository, while RubyGems.org/stats seems to show 144,034 total gems.

Repology is actually aware of them (though it only sees 141,666 of them, not sure why the discrepancy). For instance, [ruby:csvlint](https://repology.org/metapackage/ruby:csvlint/versions) is there.

However they are purposely hidden from the metapackage list (and statistics to keep it consistent, though it's really not). The idea is that repology is about packages, and projects not packaged anywhere are out of its scope. We can't do anything useful with their versions, we don't want to pollute lists with them. And there are **a lot** of them - if we unhide them, visible metapackages count will rise ~2.4 times.

In fact, this behaviour does not have any unshakable reasons behind it now - since we have powerful metapackage filtering capabilities, and I don't think anyone looks through the whole unfiltered metapackage list sequentially, extra metapackages shouldn't cause any major problems - just some PostgreSQL indexes will grow a bit. I'd prefer to keep this behavior though just to emphasize Repology focus on **packages** rather than all existing software projects.

> I thought the best way to add packages to Repology

"Adding packages to Repology" is a strange idea on its own. Repology monitors existing packages, if there's no package, it shouldn't be in Repology. If there is, but Repology isn't aware, support for new repository should be added. If you need an information on random module or other software project which is not packaged anywhere, you should likely go to its source directly. 

> I would also like to know if there are any plans on adding NPM as a repository? I would like to help if there are any plans. :)

I haven't had this in plans, but it is quite logical to add it as we already support many module collections for other languages, and some package repositories already have a lot of JS modules packaged, even through NPM culture is quite distanced from system packages concept. The only problem is its size - NPM has 4x more modules than there are metapackages known to repology now. I'm not sure such huge addition won't affect website performance, and I'm pretty sure it'll increase update time noticeably. 

So I'd gladly accept contribution of NPM support (which would consist of corresponding `repos.d` entry, fetcher (if custom one is needed) and a parser), but I it is unlikely to be enabled in production until update process is rewritten and some other bits refactored (#609, #551, #545, #478, ...), which I'm constantly thinking about, but can't guarantee to happen anytime soon.

**Comment by nemaniarjun** [comment]
Thanks for the info, I understand Repology much better now!
> And there are a lot of them - if we unhide them, visible metapackages count will rise ~2.4 times.
Maybe we can add a special parameter in search to show them ? I think the data is already fetched and stored in the DB. Might as well show it somewhere.

**Comment by AMDmi3** [comment]
> Maybe we can add a special parameter in search to show them ?

Could you please explain a use case for having these visible? I can't imagine one with repology, but if there really is, we may consider just unhiding them unconditionally.

> I think the data is already fetched and stored in the DB.

It is, but there are partial indexes which exclude them - these will grow. But repeating myself, this is unlikely to critically affect performance.

**Comment by nemaniarjun** [comment]
One of the test cases is what I am trying to do with coala. 

We are using Repology API to fetch information about the versions and corresponding available packages on different distros. 

So I will be hard coding the Repology Urls for different software to see if there is a way for us to install them without installing package managers. 

The process of finding corresponding Repology Metapackage entry is hindered by the absence of these metapackages in search.

**Comment by AMDmi3** [comment]
You don't need search to get repology urls for modules as they are named deterministically.
