### ISSUE TITLE
macOS package mangers

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#660]
As I checked you have already done a great job listing the most important macOS package managers HomeBrew, MacPorts, Nix, pkgsrc and Rudix. And I see you are also trying to add HomeBrew Cask too. There are a couple of more which might worth nothing:

1. [Fink](http://www.finkproject.org/) probably the most important one missing from the list
2. [pkgin](http://pkgin.net/) which is a binary package manager for pkgsrc
3. [MacLibre](http://www.maclibre.com/) which is kind of a poor man open source macOS app store!

P.S. I think Repology is one of the (if not THE) most important projects in the Open Source world. It is a pity that not more people know about it. I will try my best to advertise it as much as I can. Thanks a lot for your great job.

**Comment by AMDmi3** [comment]
Thanks a lot!

:construction: **Fink** there was an attempt to add it (#243, #532), and it didn't look very compatible. May revisit it.
:heavy_check_mark: **pkgin** is just a tool to manage pkgsrc packages, and pkgsrc is already [supported](https://repology.org/repository/pkgsrc_current)
:-1: **MacLibre** that only has 22 packages, hasn't updated since 2011 and website is falling apart. I don't think we want that.

Closing this as this doesn't bring up any new sources and issues for Fink already exist.
