### ISSUE TITLE
python3-pip* / pip3* not found

### ISSUE THREAD

**Issue by Mizux** [repology/repology#761]
# Context
when searching [`python3`](https://repology.org/metapackages/?search=python3&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) you be able to find the package https://repology.org/metapackage/python3/versions aka `python3*` (note: even the Arch `python` is correctly identified as `python3`)

But if you search `pip3` or `python3-pip` you'll find nothing.
Since pip is the official PyPa package manager it could be interesting to be able to list it in each repositories.

note: I only found this:
https://github.com/repology/repology-rules/blob/f2799578b3b81e31368871543b336e16dd8996cc/800.renames-and-merges/python.yaml#L152

BTW thanks for this tools ;)

**Comment by Mizux** [comment]
My bad, I should have use `python:pip`

**Comment by AMDmi3** [comment]
Yes, `python` is an exception and is split into `python2` and `python3` because of major incompatibility and the need for both versions to coexist. For most other projects suffixes and prefixes are instead removed. Python/ruby/perl/go/rust/etc modules are prefixed with e.g. `python:` just to not clash with each other.
