### ISSUE TITLE
Overlay repositories

### ISSUE THREAD

**Issue by Komzpa** [repology/repology#895]
After implementation of #892 there is a report from Arch users: they don't use AUR by itself but rather as an overlay on top of main Arch. Same story with Debian Experimental: it is usually used as "Debian Unstable + Experimental".

Here, Debian Experimental would better be "Debian Unstable + Debian Experimental" and show almost-all-green line, instead of "two packages not packaged".
![image](https://user-images.githubusercontent.com/810638/63208897-f1992c00-c0e2-11e9-8c72-e8b02f59ddab.png)

**Comment by AMDmi3** [comment]
This issue had been risen a few times already. My position is that
- I'm not going to investigate and maintain information on relationships between repositories and usecases of mixing them. In some cases, there's exponential number of combinations (for instance,  openSUSE repositories), so that's not even possible. So the goal is to convey repository information as is.
- I don't want to hide information by merging repository entries (e.g. if Unstable and Experimental are merged, there's no more knowing which repo specific project comes from) either. In Arch/AUR case it's even more important since AFAIK the way packages are installed from Arch and AUR are different.
- Repology favors feature-complete stable repositories. In the above example, neither repository complies: Unstable has outdated versions for gdal and proj, and Experimental brings unstable versions of postgis and postgresql, and since these are binary repositories, a user probably cannot have in-between configuration. In general there will be harder cases, where neither of repository and it's overlay contain up to date subset of packages, but their union look all green, while there's no technical possibility for the user to install all up to date versions at once.

Since Arch was mentioned, here's how Arch/AUR entries look like:
![1](https://user-images.githubusercontent.com/474217/63286911-c3be0e00-c2c1-11e9-853d-53fa182742e8.png)

Having merged Arch+AUR would totally hide the facts that:
- AUR has _severely_ outdated postgis, proj and protobuf-c
- Either of that
  - There are latest stable versions available for postgresql and geos
  - There are fresh unstable versions available for postgresql and geos
- User would have to carefully pick which repository to install each package from. In my understanding (which may be not correct since I'm not Arch user), to have up to date setup, user would have to install postgresql, geos, gdal, proj and protobuf-c from arch, then sfcgal from AUR, then postgis from Arch, but building it from source, and preferably editing PKGBUILD first to add missing dependency on sfcgal. Keeping this up to date will require even more manual work. So having a badge which suggests that this setup is just available with Arch+AUR would be incorrect and unfair both to users and repositories which provide equal setup out of box.

**Comment by Komzpa** [comment]
1. This can be resolved if there is a way to maintain these combination on our side, say, by having a parameter "mixtures=arch+aur,debianunstable+debianexperimental" that will just add these into table.

2. If combinations are added and are not replacing original distros, this is not an issue.

3. If the repo list is maintained on the side of badge caller, this can be resolved manually by including only combinations that make sense in context of the project.

**Comment by AMDmi3** [comment]
It would still be increased complexity on Repology side for the sake of showing misleading and incomplete information to users and favoring hard to use packaging systems. This is not going to be implemented.

NB. It seems to me that this is only really relevant for the case of sorting, as it would sink repository combinations under solid repositories. This can probably be solved by using more cleaver sorting, e.g. operating on repository groups instead of individual repositories.
