### ISSUE TITLE
The search tool doesn't show the apckage

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#929]
I hope this is not a duplicate. I tried searching the JModelica package in [the search tool](https://repology.org/projects/), however, it does n't return any results. While at least for Chocolatey there is [a package](https://chocolatey.org/packages/jmodelica). I would appreciate it if you could help me know what is the problem.

**Comment by AMDmi3** [comment]
Some repositories (including chocolatey) are treated in a way that their packages not present in any other repository are excluded from the search.

**Comment by Foadsf** [comment]
@AMDmi3 So are you saying that JModelica is being excluded because it is not available in any other repositories?! 🤔 Any reason why?

**Comment by AMDmi3** [comment]
Mostly because some repositories are too spammy. For instance, these include module collections like cpan and rubygems as well. Chocolatey is especially bad as it supplies incorrect versions and non-crossplatform software.

The project is available if you try it directly though: https://repology.org/project/jmodelica/versions

**Comment by Foadsf** [comment]
@AMDmi3 Is there any way that Chocolatey can improve the situation so its unique packages can be better trusted? 

P.S. I see there are some AUR packages with JModelica word in their explanations. Strange that they are now shown either.

**Comment by AMDmi3** [comment]
> Is there any way that Chocolatey can improve the situation so its unique packages can be better trusted?

I don't see a reason why it should - since there's nothing to compare unique package to, Repology won't be able to report anything useful apart from just citing data from chocolatey. Software not widely packaged is probably of not much interest to users either.

Theoretically, Chocolatey could signal that some software is cross-platform and thus may be added to other repositories eventually. But it won't work in practice, and we still have much better and more reliable signal - packages actually added to other repositories, after which the project is no longer hidden.

> I see there are some AUR packages with JModelica word in their explanations. Strange that they are now shown either.

What do you mean by explanations? There are no mentions of `JModelica` neither in AUR packages names nor descriptions (and Repology only search by names): https://aur.archlinux.org/packages/?O=0&K=JModelica.
